modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT for code, CC BY-NC-SA 4.0 for art"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="goat_horn_block_mod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Goat Horn Block Mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="goathorn.png" #optional
credits="Tallestred, Edmord for the goat horn block art" #optional
description='''
Adds a goat horn block.
'''
[[dependencies.goat_horn_block_mod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[44,)" #mandatory
ordering="NONE"
side="BOTH"
# Here's another dependency
[[dependencies.goat_horn_block_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"